spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sanrio?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

---

jwt:
  secret:
    key: aWRvbnR3YW50YWxvdGZvcmNocmlzbWFzdGhlcmVpc2p1c3RvbmV0aGluZ2luZWVk