spring:
  application:
    name: user-service

---

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

---

management:
  endpoints:
    web:
      exposure:
        include: health, info, mappings
  endpoint:
    health:
      show-details: always