spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

---

spring:
  cassandra:
    keyspace-name: product
    port: 9042
    contact-points: ${SPRING_CASSANDRA_CONTACT-POINTS}
    local-datacenter: dc1
    schema-action: create_if_not_exists