name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ user-service, product-service ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant permission
        working-directory: ${{ matrix.service }}
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ${{ matrix.service }}
        run: ./gradlew clean build
